language: php

services:
  - mysql
  - docker

php:
  - 7.2

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - parallel

env:
  global:
    - TYPO3_DATABASE_NAME="typo3_ci"
    - TYPO3_DATABASE_HOST="127.0.0.1"
    - TYPO3_DATABASE_USERNAME="root"
    - TYPO3_DATABASE_PASSWORD=""
    - PHP_CS_FIXER_VERSION="^2.11"
  matrix:
    - TYPO3_VERSION="^9.5"
    - TYPO3_VERSION="9.5.x-dev"
    - TYPO3_VERSION="dev-master"

matrix:
  fast_finish: true
  allow_failures:
    - env: TYPO3_VERSION="dev-master"
    - env: TYPO3_VERSION="9.5.x-dev"

before_install:
  - composer self-update
  - composer --version
  - composer validate --no-check-lock

install:
  - Build/Test/bootstrap.sh

script:
  - Build/Test/cibuild.sh
  - Build/Test/cibuild_docker.sh

after_script:
  - Build/Test/publish_coverage.sh
  - Build/Test/cleanup.sh
  - Build/Release/ter_tag_uploader.sh

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/solr/downloads
