language: php

php:
  - 5.5
  - 5.6
  - 7.0

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - parallel
      - oracle-java8-installer
env:
  global:
   - JAVA_HOME=/usr/lib/jvm/java-8-oracle
    - TYPO3_DATABASE_NAME="typo3_ci"
    - TYPO3_DATABASE_HOST="localhost"
    - TYPO3_DATABASE_USERNAME="root"
    - TYPO3_DATABASE_PASSWORD=""
  matrix:
    - TYPO3_VERSION="~7.6.9"
    - TYPO3_VERSION="~8.0.0"
    - TYPO3_VERSION="~8.1.2"
    - TYPO3_VERSION="~8.2.1"
    - TYPO3_VERSION="7.x-dev"
    - TYPO3_VERSION="dev-master"

matrix:
  fast_finish: true
  allow_failures:
    - env: TYPO3_VERSION="dev-master"
      php: 7.0
    - env: TYPO3_VERSION="~8.1.2"
      php: 7.0
    - env: TYPO3_VERSION="~8.2.1"
      php: 7.0

  exclude:
    - php: 5.5
      env: TYPO3_VERSION="dev-master"
    - php: 5.6
      env: TYPO3_VERSION="dev-master"
    - php: 5.5
      env: TYPO3_VERSION="~8.0.0"
    - php: 5.6
      env: TYPO3_VERSION="~8.0.0"
    - php: 5.5
      env: TYPO3_VERSION="~8.1.2"
    - php: 5.6
      env: TYPO3_VERSION="~8.1.2"
    - php: 5.5
      env: TYPO3_VERSION="~8.2.1"
    - php: 5.6
      env: TYPO3_VERSION="~8.2.1"
before_install:
  - composer self-update
  - composer --version
  - composer global require friendsofphp/php-cs-fixer:v1.11.7
  - composer global require namelesscoder/typo3-repository-client
  - sudo update-java-alternatives -s java-8-oracle

install:
  - Build/Test/bootstrap.sh
script:
  - Build/Test/cibuild.sh
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.unit.clover
  - php ocular.phar code-coverage:upload --format=php-clover coverage.integration.clover
  - Build/Test/cleanup.sh
  - Build/Release/ter_tag_uploader.sh
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/solr/downloads
